sudo: required
language: python
cache: pip

services: 
  - docker

python:
  - "3.6"
  
install:
  - pip install mypy
  - pip install -r requirements.txt
  - pip install .

script:
  - mypy -m bench --strict

  # Run the little-book-of-semaphores example (remote execution)
  - examples/little-book-of-semaphores.sh

  # Run the local examples
  - pip install -r examples/local_test/src/requirements.txt
  - cd examples/local_test && python3 run_test.py
