sudo: required
language: python
cache: pip

services: 
  - docker

python:
  - "3.6"

env:
  - LOCAL_EXAMPLES=1 LITTLE_BOOK=0
  - LOCAL_EXAMPLES=0 LITTLE_BOOK=1

install:
  - pip install mypy -r requirements.txt
  - pip install .

script:
  - mypy -m bench --strict

  # Run the little-book-of-semaphores example (remote execution)
  - if [ $LITTLE_BOOK == 1]; then examples/little-book-of-semaphores.sh; fi

  # Run the local examples
  - if [ $LOCAL_EXAMPLES == 1 ]; then pip install -r examples/local_test/src/requirements.txt; fi
  - if [ $LOCAL_EXAMPLES == 1 ]; then cd examples/local_test && python3 run_test.py; fi
