sudo: required
language: python
cache: pip

services: 
  - docker

python:
  - "3.6"
  
install:
  - pip install mypy
  - pip install -r requirements.txt
  - pip install .

script:
  - mypy -m bench --strict
  - examples/little-book-of-semaphores.sh 
